apiVersion: apps/v1
kind: Deployment
metadata:
  name: tetris-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tetris-app
  template:
    metadata:
      labels:
        app: tetris-app
    spec:
      containers:
      - name: tetris-app
        image: my-tetris-app
        ports:
        - containerPort: 80
