name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: |
        docker build -t my-tetris-app .

    - name: Install Minikube
      run: |
        curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 \
          && chmod +x minikube \
          && sudo mv minikube /usr/local/bin/

    - name: Start Minikube
      run: |
        minikube start --driver=docker

    - name: Set Kubernetes context
      run: |
        kubectl config use-context minikube

    - name: Load Docker image into Minikube
      run: |
        minikube image load my-tetris-app

    - name: Deploy to Minikube
      run: |
        kubectl apply -f k8s/deployment.yml
        kubectl apply -f k8s/service.yml
